- hosts: all
  tasks:
 
    - name: create env file
      ansible.builtin.template:
        src: templates/env.j2
        dest: /.env
        mode: '0644'
    
    - community.docker.docker_container:
        name: redmine
        image: redmine
        env_file: /.env
        restart_policy: always
        state: started
        ports:
          - 3000:3000
        