---
- name: Setup
  hosts: webservers
  tasks:

    - name: install pip
      import_role:
        name: geerlingguy.pip
      become: yes
      tags: pip

    - name: install docker
      import_role:
        name: geerlingguy.docker
      become: yes
      tags: docker

    - name: install datadog
      import_role:
        name: datadog.datadog
      vars:
        datadog_api_key: "{{ dd_api_key }}"
        datadog_site: "{{ dd_site }}"
      become: yes
      tags: datadog
